### ISSUE TITLE
How much resource usage ?

### ISSUE THREAD

**Issue by muhfaris** [afaqurk/mysql-monitor#1]
hi, 
i have small vps with ram 1Gb, and swap 1Gb. can i use this for my small vps

thanks

**Comment by tariqbuilds** [comment]
this app is more network intensive than RAM. 1GB of RAM should be more than enough to run this on a server. It is a very simple node.js process under the hood. 

If you run into any resource issues, feel free to post it here and maybe it can be addressed.
